---
format:
  html:
    code-copy: true
    code-overflow: wrap
---

::::: grid-container
:::: grid-nocol
## Conditions d'utilisation

### Conditions générales

L'ensemble des ressources présentées sur ce site web (visualisastions interactives, images, textes, bases de données) peuvent être librement utilisées dans les conditions prévues par la licence **Creative Commons CC BY-SA 4.0 Deed**

::: callout-important
#### Vous êtes libre de

**Partager** - copier, distribuer et communiquer le matériel par tous moyens et sous tous formats pour toute utilisation, y compris commerciale.

**Adapter** - remixer, transformer et créer à partir du matériel pour toute utilisation, y compris commerciale.

L'Offrant ne peut retirer les autorisations concédées par la licence tant que vous appliquez les termes de cette licence.

#### Sous les conditions suivantes :

**Attribution** - Vous devez créditer l'Œuvre, intégrer un lien vers la licence et indiquer si des modifications ont été effectuées à l'œuvre. Vous devez indiquer ces informations par tous les moyens raisonnables, sans toutefois suggérer que l'Offrant vous soutient ou soutient la façon dont vous avez utilisé son Oeuvre.

**Partage dans les Mêmes Conditions** - Dans le cas où vous effectuez un remix, que vous transformez, ou créez à partir du matériel composant l'œuvre originale, vous devez diffuser l'œuvre modifiée dans les même conditions, c'est à dire avec la même licence avec laquelle l'œuvre originale a été diffusée.

**Pas de restrictions complémentaires** - Vous n'êtes pas autorisé à appliquer des conditions légales ou des mesures techniques qui restreindraient légalement autrui à utiliser l'œuvre dans les conditions décrites par la licence.

#### Notes :

Vous n'êtes pas dans l'obligation de respecter la licence pour les éléments ou matériel appartenant au domaine public ou dans le cas où l'utilisation que vous souhaitez faire est couverte par une exception .

Aucune garantie n'est donnée. Il se peut que la licence ne vous donne pas toutes les permissions nécessaires pour votre utilisation. Par exemple, certains droits comme les droits moraux, le droit des données personnelles et le droit à l'image sont susceptibles de limiter votre utilisation.
:::

Pour citer le site-internet : *Citation à venir...*

### Propriété intellectuelle


::::
:::::