project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!maquettes/"
    - "!template.qmd"
  
website:
  title: "Atlas Intéractif IMAGEUN"
  site-url: https://imageun.gitpages.huma-num.fr/atlas_quarto/
  description: "Atlas Intéractif du projet ANR-DFG IMAGEUN"
  page-footer: Atlas Interactif - IMAGEUN · 2024 - [![licensebuttons by-nc-sa](https://licensebuttons.net/l/by-nc-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0/deed.fr) - CIST
  sidebar: false
  navbar:
    collapse: false
    left:
      - href: documents/macroregion.qmd
        text: Imaginaires macrorégionaux
      - text: Terrains d'enquêtes
        menu: 
          - href: documents/france.qmd
            text: Where is France
          - href: documents/germany.qmd
            text: Where is Germany
          - href: documents/antilles.qmd
            text: Where is French Caribbean
          - href: documents/tunisia.qmd
            text: Where is Tunisia
          - href: documents/turkey.qmd
            text: Where is Turkey
      - text: Sur l'europe et l'UE
        menu: 
          - href: documents/whereEurope.qmd
            text: Where is Europe
      - href: widgets.qmd
        text: Widgets
    right: 
      # - href: docs/about.qmd
      #   text: A propos
      - href: documents/legal.qmd
        text: Mentions légales
      - href: documents/usage.qmd
        text: Conditions d'utilisation

          
format:
  html:
    citations-hover: false
    theme: [cerulean, style.scss]
    toc: false
    page-layout: full
    execute:
      warning: false
      message: false 
      echo: false
      code-line-numbers: false
      
editor_options: 
  chunk_output_type: console

editor: source

